ros2/domain_bridge

- src/domain_bridge/domain_bridge.cpp
- src/domain_bridge/topic_bridge.hpp
- test/domain_bridge/test_domain_bridge.cpp
The first commit fixes a bug: f6dedb6
The second commit refactors the less-than logic as an operator of the struct: 40a4ffd
> Fix topic bridge less operator

- doc/design.md
- src/domain_bridge/domain_bridge.cpp
- src/domain_bridge/wait_for_qos_handler.hpp
- test/CMakeLists.txt
- test/domain_bridge/test_domain_bridge.cpp
- test/domain_bridge/test_qos_matching.cpp
I've updated the design doc to reflect the implementation.
Specifically, this change introduces a `WaitForQosHandler` class used for deferring topic bridge creation. It creates a thread for each topic bridge to wait for at least one publisher to be available. Once a publisher is available it signals to the domain bridge via a callback, and a topic bridge is created.
In the special case of more than one publisher with different QoS settings, I've adopted a similar approach as rosbag2 for selecting a QoS that is compatible with most of the available publishers. Note, we could factor out this logic following https://github.com/ros2/rosbag2/issues/601 and/or https://github.com/ros2/rmw/issues/304.
> Automatically match QoS settings across the bridge

- CMakeLists.txt
- README.md
- examples/example_bridge_config.yaml
- package.xml
- src/domain_bridge.cpp
- test/CMakeLists.txt
- test/test_domain_bridge.launch.py
- Add options for overriding 'from' and 'to' domain IDs from the CLI (7e14198)
- Add launch tests for executable (2d2171e)
- Add example config (also validated by tests) (3902e3d)
- Updated README (9cfc223)
Depends on https://github.com/ros2/domain_bridge/pull/6
> Add '--from' and '--to' options to executable + add tests

- .github/workflows/build_and_test.yaml
- .github/workflows/ci.repos
- CMakeLists.txt
- doc/design.md
- examples/example_bridge_config.yaml
- include/domain_bridge/parse_domain_bridge_yaml_config.hpp
- include/domain_bridge/qos_options.hpp
- include/domain_bridge/topic_bridge_options.hpp
- package.xml
- src/domain_bridge/domain_bridge.cpp
- src/domain_bridge/parse_domain_bridge_yaml_config.cpp
- src/domain_bridge/qos_options.cpp
- src/domain_bridge/topic_bridge_options.cpp
- test/domain_bridge/config/invalid_depth.yaml
- test/domain_bridge/config/invalid_durability.yaml
- test/domain_bridge/config/invalid_history.yaml
- test/domain_bridge/config/invalid_reliability.yaml
- test/domain_bridge/config/qos_as_list.yaml
- test/domain_bridge/config/topic_options.yaml
- test/domain_bridge/test_parse_domain_bridge_yaml_config.cpp
- test/domain_bridge/test_qos_matching.cpp
Resolves https://github.com/ros2/domain_bridge/issues/8
* Adds support for configuring QoS policies per topic bridge.
* Adds YAML support
* Change default value for deadline and lifespan policies to be "infinite"
* Users can opt-in to the automatic matching
> Add QoS overriding

- doc/design.md
- include/domain_bridge/qos_options.hpp
Default to the RMW default value.
This fixes an issue with Connext, which does not handle the same maximum
value as other RMWs.
Fixes https://github.com/ros2/domain_bridge/issues/14
> Change default value of deadline and lifespan

- CMakeLists.txt
It seems that this may not be necessary with GCC 9, but stdc++fs isn't part of libstdc++ prior to that.
Should unblock RHEL builds: https://build.ros2.org/job/Rbin_rhel_el864__domain_bridge__rhel_8_x86_64__binary/4/console
Is there any CI I should trigger for this change?
> Add explicit link against stdc++fs

- test/CMakeLists.txt
During colcon builds, colcon is using the CMAKE_INSTALL_PREFIX to dictate where the files should be installed to. During Debian and RPM builds, the DESTDIR environment variable is used. The latter approach prefixes all of the install paths, including absolute paths like the destination for the test test resource installation.
The end result is that they get installed into the staging directory for the platform package, and typically end up in the package at some unexpected location.
For RPM builds, this is a fatal build failure, as ROS packages are not expected to install anything outside of /opt/ros/<foo>.
It doesn't appear that installing these resources is even necessary because the working directory of the test means that they're already available to the test that needs them without …
> Stop installing test resources

- src/domain_bridge/wait_for_qos_handler.hpp
I've observed in larger systems sometimes the RMW layer will return an error when trying to query publisher info.
If this happens, rclcpp throws an RCLError exception and the domain bridge crashes. I have not been able to
reliable reproduce this exception, but it seems to happen during the discovery phase. I've only observed it using rmw_connext_cpp.
In any case, it seems reasonable to log an error instead of throwing an exception so that the domain bridge threads can keep working.
> Do not crash if there's an error querying endpoint info

- src/domain_bridge/generic_subscription.cpp
- src/domain_bridge/generic_subscription.hpp
This should allow it to build against rolling again.
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>
This has been failing in Rolling for a couple of weeks now: https://build.ros2.org/view/Rbin_uF64/job/Rbin_uF64__domain_bridge__ubuntu_focal_amd64__binary/
Note that this change is *not* backwards-compatible with Galactic, so we'll have to branch off for Galactic to take this fix.
> Override handle_serialized_message.

- src/domain_bridge/generic_subscription.cpp
We need to implement `handle_serialized_message()` and not `handle_message()` in `GenericSubscription`.
I think the bug was introduced in https://github.com/ros2/domain_bridge/pull/21 after https://github.com/ros2/rclcpp/pull/1557.
> Fix bug in generic subscription

- src/domain_bridge.cpp
- src/domain_bridge_rti_qos.cpp
- src/process_cmd_line_arguments.hpp
I also moved the command line arguments parsing logic to a common function, that can be reused in both `domain_bridge` and `domain_bridge_rti_qos`.
> Add `--mode` argument to `domain_bridge`

- README.md
- examples/example_bridge_config.yaml
- include/domain_bridge/topic_bridge_options.hpp
- src/domain_bridge/domain_bridge.cpp
- src/domain_bridge/parse_domain_bridge_yaml_config.cpp
- src/domain_bridge/topic_bridge_options.cpp
- test/domain_bridge/config/topic_options.yaml
- test/domain_bridge/test_domain_bridge.cpp
- test/domain_bridge/test_domain_bridge_end_to_end.cpp
- test/domain_bridge/test_parse_domain_bridge_yaml_config.cpp
As a follow-up to #39, this PR adds an option to reverse the _from_ and _to_ domain IDs when bridging a topic.
> Add reverse option to swap `from` and `to` domain IDs

- src/domain_bridge/wait_for_graph_events.hpp
Also check the vector of service callbacks when deciding if we should continue
executing the wait loop in WaitforGraphEvents threads.
Fixes https://github.com/ros2/domain_bridge/issues/41
> Fix bug when waiting for service to be available

- package.xml
- test/CMakeLists.txt
Follow-up to https://github.com/ros2/domain_bridge/issues/41.
Hopefully this will prevent regressions for RMWs that are not the ROS 2 default.
> Run communication-related tests with all available RMWs

- include/domain_bridge/service_bridge_impl.inc
Replaces https://github.com/ros2/domain_bridge/pull/48.
Multiple inheritance with `std::enable_shared_from_this` is problematic, see:
- https://stackoverflow.com/questions/16082785/use-of-enable-shared-from-this-with-multiple-inheritance
- https://stackoverflow.com/questions/15549722/double-inheritance-of-enable-shared-from-this
- https://stackoverflow.com/questions/12790859/bad-weak-pointer-when-base-and-derived-class-both-inherit-from-boostenable-sha
- https://stackoverflow.com/questions/14939190/boost-shared-from-this-and-multiple-inheritance
The solutions proposed in those threads cannot directly applied here.
To avoid the issue, I'm using the support for defering responses in services added in rclcpp, avoiding the need of using `std::enable_shared_from_this` all together.
We will …
> Use defered service support in rclcpp

- CMakeLists.txt
Locally, I get an error without this patch:
```
[Processing: domain_bridge]
--- stderr: domain_bridge
/home/ivanpauno/ros2_ws/other_ws/domain_bridge_ws/src/domain_bridge/test/domain_bridge/test_component.cpp:16:10: fatal error: rclcpp_components/register_node_macro.hpp: No such file or directory
16 | #include "rclcpp_components/register_node_macro.hpp"
|          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/domain_bridge_test_component_lib.dir/build.make:63: CMakeFiles/domain_bridge_test_component_lib.dir/test/domain_bridge/test_component.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:705: CMakeFiles/domain_bridge_test_component_lib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make: *** [Makefile:141: all] Error 2
```
CI …
> Add missing dependency in test_component_lib

- CMakeLists.txt
Otherwise, downstream targets will try to link against it.
This can cause issues linking because the test component library is not exporting dependencies (e.g. test_msgs).
> Do not associate test library with export

- include/domain_bridge/process_cmd_line_arguments.hpp
- include/domain_bridge/topic_bridge_options.hpp
- package.xml
- src/domain_bridge/domain_bridge.cpp
- src/domain_bridge/topic_bridge_options.cpp
- src/domain_bridge/wait_for_graph_events.hpp
- test/domain_bridge/test_domain_bridge_end_to_end.cpp
The callbacks added to the `WaitForGraphEvents` object are now kept forever instead of being removed after the first time they are called.
There might be another way to get this working (register callback waiting for publishing/subscription, remove it and register the one waiting for publisher/subscription/removed, ...), though I find that more complex to implement in the current code.
> Auto remove bridge when endpoint removed

- include/domain_bridge/parse_domain_bridge_yaml_config.hpp
Prior to this patch, the `\see` tag would render a `See also` section in
the middle of a running sentence, and hence would look out-of-place.
Signed-off-by: Abrar Rahman Protyasha <aprotyas@u.rochester.edu>
> [domain_bridge] Improve doxygen docblock layout

- include/domain_bridge/service_bridge_impl.inc
Pass rclcpp instance instead of rmw instance to create_client and create_service methods.
> Fix deprecation warnings

- .github/workflows/build_and_test.yaml
Related PRs:
- https://github.com/ros/rosdistro/pull/34699
- https://github.com/ros2-gbp/domain_bridge-release/pull/1
> [humble] Update CI to target Humble
